'''
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
addict                    2.4.0                    pypi_0    pypi
aiohappyeyeballs          2.4.4                    pypi_0    pypi
aiohttp                   3.11.11                  pypi_0    pypi
aiosignal                 1.3.2                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
async-timeout             5.0.1                    pypi_0    pypi
attrs                     24.3.0                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blenderproc               2.8.0                    pypi_0    pypi
blessed                   1.20.0                   pypi_0    pypi
ca-certificates           2024.12.14           hbcca054_0    conda-forge
certifi                   2024.12.14               pypi_0    pypi
charset-normalizer        3.4.1                    pypi_0    pypi
cmake                     3.31.2                   pypi_0    pypi
colorlog                  6.9.0                    pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
distinctipy               1.3.4                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
fonttools                 4.55.3                   pypi_0    pypi
freetype-py               2.5.1                    pypi_0    pypi
frozenlist                1.5.0                    pypi_0    pypi
fsspec                    2024.12.0                pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
gdown                     5.2.0                    pypi_0    pypi
gorilla-core              0.2.7.8                  pypi_0    pypi
gpustat                   1.0.0                    pypi_0    pypi
h5py                      3.12.1                   pypi_0    pypi
huggingface-hub           0.27.0                   pypi_0    pypi
hydra-colorlog            1.2.0                    pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
idna                      3.10                     pypi_0    pypi
imageio                   2.36.1                   pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
jinja2                    3.1.5                    pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
liblzma                   5.6.3                hb9d3cd8_1    conda-forge
liblzma-devel             5.6.3                hb9d3cd8_1    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lightning-utilities       0.11.9                   pypi_0    pypi
lit                       18.1.8                   pypi_0    pypi
lmdb                      1.5.1                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
matplotlib                3.9.4                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
networkx                  3.2.1                    pypi_0    pypi
numpy                     1.23.0                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-ml-py              11.495.46                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openssl                   1.1.1w               hd590300_0    conda-forge
packaging                 24.2                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
pillow                    11.0.0                   pypi_0    pypi
pip                       24.3.1             pyh8b19718_2    conda-forge
platformdirs              4.3.6                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
pointnet2                 0.0.0                    pypi_0    pypi
portalocker               3.0.0                    pypi_0    pypi
progressbar               2.5                      pypi_0    pypi
propcache                 0.2.1                    pypi_0    pypi
protobuf                  5.29.2                   pypi_0    pypi
psutil                    6.1.1                    pypi_0    pypi
pycocotools               2.0.8                    pypi_0    pypi
pyglet                    2.0.20                   pypi_0    pypi
pynvml                    11.5.3                   pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pyre-extensions           0.0.23                   pypi_0    pypi
pyrender                  0.1.45                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
pytest                    8.3.4                    pypi_0    pypi
python                    3.9.6           h49503c6_1_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch-lightning         2.3.3                    pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3                   pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.12                   pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
segment-anything          1.0                      pypi_0    pypi
setuptools                75.6.0             pyhff2d567_1    conda-forge
shapely                   2.0.6                    pypi_0    pypi
six                       1.17.0                   pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
sympy                     1.13.3                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
termcolor                 2.5.0                    pypi_0    pypi
tifffile                  2024.8.30                pypi_0    pypi
timm                      1.0.12                   pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.2.1                    pypi_0    pypi
torch                     2.0.0+cu118              pypi_0    pypi
torchaudio                2.0.1+cu118              pypi_0    pypi
torchmetrics              0.10.3                   pypi_0    pypi
torchvision               0.15.1+cu118             pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
trimesh                   4.0.8                    pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
ultralytics               8.0.135                  pypi_0    pypi
urllib3                   2.3.0                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
xformers                  0.0.18                   pypi_0    pypi
xz                        5.6.3                hbcc6ac9_1    conda-forge
xz-gpl-tools              5.6.3                hbcc6ac9_1    conda-forge
xz-tools                  5.6.3                hb9d3cd8_1    conda-forge
yacs                      0.1.8                    pypi_0    pypi
yapf                      0.43.0                   pypi_0    pypi
yarl                      1.18.3                   pypi_0    pypi
zipp                      3.21.0                   pypi_0    pypi
zlib                      1.2.13               h4ab18f5_6    conda-forge




'''